src/fantasyplayers2/fantasyplayers2/Models/ErrorViewModel.cs
using System;

namespace StraussDa.fantasyplayers2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/fantasyplayers2/fantasyplayers2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StraussDa.fantasyplayers2.Models;

namespace StraussDa.fantasyplayers2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/fantasyplayers2/fantasyplayers2/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StraussDa.ApplicationCore.Entities;
using StraussDa.ApplicationCore.Interfaces;

namespace Web.Controllers
{
    public class PlayerController : Controller
    {
        private readonly IPlayerRepository _pRepo;

        public PlayerController(IPlayerRepository pRepo)
        {
            _pRepo = pRepo;
        }
        // GET: Player
        public ActionResult Index()
        {
            return View(_pRepo.ListAll());
        }

        // GET: Player/Details/5
        public ActionResult Details(int id)
        {
            return View(_pRepo.GetById(id));
        }

        // GET: Player/Create
        public ActionResult Create()
        {
            return View(new Player());
        }

        // POST: Player/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Player newPlayer)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    _pRepo.Add(newPlayer);
                    return RedirectToAction(nameof(Index));
                }


                
            }
            catch(Exception ex)
            {
               //TODO LOG THE ERROR
            }

            return View(newPlayer);
        }

        // GET: Player/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_pRepo.GetById(id));
        }

        // POST: Player/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Player editedPlayer)
        {
            try
            {
                _pRepo.Edit(editedPlayer);

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                //TODO Log the Exception
            }
            return View(editedPlayer);
        }

        // GET: Player/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_pRepo.GetById(id));
        }

        // POST: Player/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Player deletedPlayer)
        {
            try
            {
                _pRepo.Delete(deletedPlayer);

                return RedirectToAction(nameof(Index));
            }
            catch(Exception)
            {
                //TODO Log Exception
            }
            return View(deletedPlayer);
        }
    }
}

src/fantasyplayers2/fantasyplayers2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/fantasyplayers2/fantasyplayers2/Views/Player/Create.cshtml
@model StraussDa.ApplicationCore.Entities.Player

@{
    ViewData["Title"] = "Create a telgram";
    ViewData["Action"] = "Create";
}

<h1>Create</h1>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
    @Html.Partial("_EditPlayer", Model, ViewData)
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/fantasyplayers2/fantasyplayers2/Views/Player/Delete.cshtml
@model StraussDa.ApplicationCore.Entities.Player

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Player</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Team)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PosRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PosRank)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/fantasyplayers2/fantasyplayers2/Views/Player/Details.cshtml
@model StraussDa.ApplicationCore.Entities.Player

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Team)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PosRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PosRank)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

src/fantasyplayers2/fantasyplayers2/Views/Player/Edit.cshtml
@model StraussDa.ApplicationCore.Entities.Player

@{
    ViewData["Action"] = "Edit";
    ViewData["Title"] = "Edit a Telgram";
}

<h1>Edit</h1>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @Html.Partial("_EditPlayer", Model, ViewData)
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/fantasyplayers2/fantasyplayers2/Views/Player/Index.cshtml
@model IEnumerable<StraussDa.ApplicationCore.Entities.Player>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Team)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PosRank)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Team)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PosRank)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id  }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

src/fantasyplayers2/fantasyplayers2/Views/Player/_EditPlayer.cshtml
@model StraussDa.ApplicationCore.Entities.Player

<form asp-action="@ViewData["Action"]">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="FirstName" class="control-label"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="control-label"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Team" class="control-label"></label>
        <input asp-for="Team" class="form-control" />
        <span asp-validation-for="Team" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Pos" class="control-label"></label>
        <input asp-for="Pos" class="form-control" />
        <span asp-validation-for="Pos" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PosRank" class="control-label"></label>
        <input asp-for="PosRank" class="form-control" />
        <span asp-validation-for="PosRank" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

src/fantasyplayers2/fantasyplayers2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - fantasyplayers2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">fantasyplayers2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - fantasyplayers2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>